include $(TOPDIR)/rules.mk

PKG_VERSION:=1.25.0

LUCI_TITLE:=LuCI Support for nikki
LUCI_DEPENDS:=+luci-base +nikki +libsqlite3 +curl +jsonfilter

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature